START_VP_COINS = 5

NOTIFICATIONS_PER_PAGE = 30
VIDEOS_PER_PAGE = 30
BATTLES_PER_PAGE = 30

BATTLE_DURATION_DAY = 1

REQUIRED_TAG = "vpch"

AWARD_FOR_VICTORY = 10
DISCARD_FOR_LOSS = -5

WIN_RANKING_CHANGE = 100
LOSE_RANKING_CHANGE = 10
